### PR TITLE
Merge OSM Visual History

### PR DESCRIPTION
**Pull request by willemarcel**
I changed the name back to OSM Deep History

### CODE REVIEW

**Comment by iandees** [comment]
Thanks for putting together this PR, @willemarcel.

I noticed you removed the Apache license and didn't put a different one in its place. Did you have a different license in mind? If you don't mind I'll probably put an MIT license back in its place.

I'll try building this locally and then will merge it later today.

**Comment by willemarcel** [comment]
@iandees the license was changed by @aleung

**Comment by aleung** [comment]
@willemarcel @iandees  I haven't changed license. See https://github.com/osmlab/osm-deep-history/issues/15

**Comment by aleung** [comment]
Reference to previous discussion on merge back: #14

**Comment by willemarcel** [comment]
Sorry, @aleung. You're right, the deleted LICENSE file was Apache, but the license in the package.json always was BSD. So @iandees you can set the license you prefer

**Pull request merged**
